//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaso.Properties {


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default {
			get {
				return defaultInstance;
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.mp3</string>
  <string>.wav</string>
  <string>.wma</string>
  <string>.acc</string>
  <string>.ogg</string>
  <string>.flac</string>
</ArrayOfString>")]
		public global::System.Collections.Specialized.StringCollection AudioFileExtensions {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["AudioFileExtensions"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.wmv</string>
  <string>.avi</string>
  <string>.mpg</string>
  <string>.mpeg</string>
  <string>.mpa</string>
  <string>.asf</string>
  <string>.mov</string>
  <string>.mp4</string>
  <string>.mts</string>
  <string>.m4v</string>
  <string>.m2v</string>
</ArrayOfString>")]
		public global::System.Collections.Specialized.StringCollection VideoFileExtensions {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["VideoFileExtensions"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.txt</string>
  <string>.doc</string>
  <string>.docx</string>
  <string>.odt</string>
  <string>.rtf</string>
  <string>.htm</string>
  <string>.html</string>
  <string>.pdf</string>
</ArrayOfString>")]
		public global::System.Collections.Specialized.StringCollection TextFileExtensions {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["TextFileExtensions"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.jpg</string>
  <string>.jpeg</string>
  <string>.gif</string>
  <string>.tif</string>
  <string>.png</string>
  <string>.bmp</string>
  <string>.dib</string>
</ArrayOfString>")]
		public global::System.Collections.Specialized.StringCollection ImageFileExtensions {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["ImageFileExtensions"]));
			}
		}
	}
}
