//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaso.Reporting {


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
	internal sealed partial class ReportingSetting : global::System.Configuration.ApplicationSettingsBase {

		private static ReportingSetting defaultInstance = ((ReportingSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReportingSetting())));

		public static ReportingSetting Default {
			get {
				return defaultInstance;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1")]
		public uint Launches {
			get {
				return ((uint)(this["Launches"]));
			}
			set {
				this["Launches"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string UserIdentifier {
			get {
				return ((string)(this["UserIdentifier"]));
			}
			set {
				this["UserIdentifier"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.DateTime LastLaunchDate {
			get {
				return ((global::System.DateTime)(this["LastLaunchDate"]));
			}
			set {
				this["LastLaunchDate"] = value;
			}
		}
	}
}
