//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Windows.Forms.ImageToolbox {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ImageToolboxSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ImageToolboxSettings defaultInstance = ((ImageToolboxSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ImageToolboxSettings())));
        
        public static ImageToolboxSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastImageFolder {
            get {
                return ((string)(this["LastImageFolder"]));
            }
            set {
                this["LastImageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DisabledImageCollections {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DisabledImageCollections"]));
            }
            set {
                this["DisabledImageCollections"] = value;
            }
        }
    }
}
