//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.DblBundle.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.DblBundle.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] English_lds {
            get {
                object obj = ResourceManager.GetObject("English_lds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ldml&gt;
        ///	&lt;identity&gt;
        ///		&lt;version number=&quot;&quot; /&gt;
        ///		&lt;generation date=&quot;2015-07-09T20:55:53Z&quot; /&gt;
        ///		&lt;language type=&quot;qaa&quot; /&gt;
        ///	&lt;/identity&gt;
        ///	&lt;delimiters&gt;
        ///		&lt;quotationStart&gt;“&lt;/quotationStart&gt;
        ///		&lt;quotationEnd&gt;”&lt;/quotationEnd&gt;
        ///		&lt;alternateQuotationStart&gt;‘&lt;/alternateQuotationStart&gt;
        ///		&lt;alternateQuotationEnd&gt;’&lt;/alternateQuotationEnd&gt;
        ///		&lt;special xmlns:sil=&quot;urn://www.sil.org/ldml/0.1&quot;&gt;
        ///			&lt;sil:quotation-marks&gt;
        ///				&lt;sil:quotationContinue&gt;“&lt;/sil:quotationContinue&gt;
        ///				&lt;sil:alt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ldml_xml {
            get {
                return ResourceManager.GetString("ldml_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MAT_usx {
            get {
                object obj = ResourceManager.GetObject("MAT_usx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DBLMetadata type=&quot;text&quot; typeVersion=&quot;1.4&quot; id=&quot;ce61dd3decd6b8a8&quot; revision=&quot;0&quot;&gt;
        ///  &lt;identification&gt;
        ///    &lt;name&gt;Test Bundle Publication&lt;/name&gt;
        ///    &lt;nameLocal&gt;&lt;/nameLocal&gt;
        ///    &lt;abbreviation&gt;&lt;/abbreviation&gt;
        ///    &lt;abbreviationLocal&gt;&lt;/abbreviationLocal&gt;
        ///    &lt;scope&gt;&lt;/scope&gt;
        ///    &lt;description&gt;&lt;/description&gt;
        ///    &lt;dateCompleted&gt;&lt;/dateCompleted&gt;
        ///    &lt;systemId type=&quot;gbc&quot;&gt;&lt;/systemId&gt;
        ///    &lt;systemId type=&quot;tms&quot;&gt;&lt;/systemId&gt;
        ///    &lt;systemId type=&quot;reap&quot;&gt;&lt;/systemId&gt;
        ///    &lt;systemId t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metadata_xml {
            get {
                return ResourceManager.GetString("metadata_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DBLMetadata version=&quot;2.1&quot; id=&quot;7881095a69332502&quot; revision=&quot;&quot;&gt;
        ///  &lt;identification&gt;
        ///    &lt;name&gt;Ri utzilaj tzij re ri kanimajawal Jesucristo&lt;/name&gt;
        ///    &lt;description&gt;New Testament in Achi Rabinal; acr (GT:acrN:Achi)&lt;/description&gt;
        ///    &lt;abbreviation&gt;acrNNT&lt;/abbreviation&gt;
        ///    &lt;scope&gt;New Testament&lt;/scope&gt;
        ///    &lt;dateCompleted&gt;2009&lt;/dateCompleted&gt;
        ///    &lt;bundleProducer&gt;Paratext/7.4.100.9&lt;/bundleProducer&gt;
        ///    &lt;systemId type=&quot;paratext&quot;&gt;
        ///      &lt;id&gt;7881095a69332502ec7b3544a7e4e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metadataVersion2_1_xml {
            get {
                return ResourceManager.GetString("metadataVersion2_1_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;stylesheet&gt;
        ///  &lt;property name=&quot;font-family&quot;&gt;Cambria&lt;/property&gt;
        ///  &lt;property name=&quot;font-size&quot; unit=&quot;pt&quot;&gt;14&lt;/property&gt;
        ///  &lt;style id=&quot;id&quot; publishable=&quot;false&quot; versetext=&quot;false&quot;&gt;
        ///    &lt;name&gt;id - File - Identification&lt;/name&gt;
        ///    &lt;description&gt;File identification information (BOOKID, FILENAME, EDITOR, MODIFICATION DATE)&lt;/description&gt;
        ///    &lt;property name=&quot;text-align&quot;&gt;left&lt;/property&gt;
        ///  &lt;/style&gt;
        ///  &lt;style id=&quot;h&quot; publishable=&quot;true&quot; versetext=&quot;false&quot;&gt;
        ///    &lt;name&gt;h - File - Head [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles_xml {
            get {
                return ResourceManager.GetString("styles_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] versification_vrs {
            get {
                object obj = ResourceManager.GetObject("versification_vrs", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
