//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.DblBundle.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.DblBundle.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DBLMetadata type=&quot;text&quot; typeVersion=&quot;1.5&quot; id=&quot;3b9fdc679b9319c3&quot; revision=&quot;2&quot;&gt;
        ///  &lt;identification&gt;
        ///    &lt;name&gt;Acholi New Testament 1985&lt;/name&gt;
        ///    &lt;nameLocal&gt;Acoli Baibul 1985&lt;/nameLocal&gt;
        ///    &lt;abbreviation&gt;ACHBI85&lt;/abbreviation&gt;
        ///    &lt;abbreviationLocal&gt;Aco85&lt;/abbreviationLocal&gt;
        ///    &lt;scope&gt;New Testament&lt;/scope&gt;
        ///    &lt;description&gt;Acholi: Acholi New Testament 1985 New Testament only&lt;/description&gt;
        ///    &lt;dateCompleted/&gt;
        ///    &lt;systemId type=&quot;tms&quot;&gt;b9236acd-66f3-44d0-98fc-3970b3d017cd&lt;/sys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcholiMetadataVersion1_5_xml {
            get {
                return ResourceManager.GetString("AcholiMetadataVersion1_5_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DBLMetadata version=&quot;2.1&quot; id=&quot;3b9fdc679b9319c3&quot; revision=&quot;2&quot;&gt;
        ///  &lt;identification&gt;
        ///    &lt;name&gt;Acholi New Testament 1985&lt;/name&gt;
        ///    &lt;nameLocal&gt;Acoli Baibul 1985&lt;/nameLocal&gt;
        ///    &lt;description&gt;Acholi: Acholi New Testament 1985 New Testament only&lt;/description&gt;
        ///    &lt;abbreviation&gt;ACHBI85&lt;/abbreviation&gt;
        ///    &lt;abbreviationLocal&gt;Aco85&lt;/abbreviationLocal&gt;
        ///    &lt;scope&gt;New Testament&lt;/scope&gt;
        ///    &lt;bundleProducer&gt;Paratext/7.4.500.59&lt;/bundleProducer&gt;
        ///    &lt;systemId type=&quot;tms&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcholiMetadataVersion2_1_xml {
            get {
                return ResourceManager.GetString("AcholiMetadataVersion2_1_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] English_lds {
            get {
                object obj = ResourceManager.GetObject("English_lds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ldml&gt;
        ///	&lt;identity&gt;
        ///		&lt;version number=&quot;&quot; /&gt;
        ///		&lt;generation date=&quot;2015-07-09T20:55:53Z&quot; /&gt;
        ///		&lt;language type=&quot;qaa&quot; /&gt;
        ///	&lt;/identity&gt;
        ///	&lt;delimiters&gt;
        ///		&lt;quotationStart&gt;“&lt;/quotationStart&gt;
        ///		&lt;quotationEnd&gt;”&lt;/quotationEnd&gt;
        ///		&lt;alternateQuotationStart&gt;‘&lt;/alternateQuotationStart&gt;
        ///		&lt;alternateQuotationEnd&gt;’&lt;/alternateQuotationEnd&gt;
        ///		&lt;special xmlns:sil=&quot;urn://www.sil.org/ldml/0.1&quot;&gt;
        ///			&lt;sil:quotation-marks&gt;
        ///				&lt;sil:quotationContinue&gt;“&lt;/sil:quotationContinue&gt;
        ///				&lt;sil:alt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ldml_xml {
            get {
                return ResourceManager.GetString("ldml_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MAT_usx {
            get {
                object obj = ResourceManager.GetObject("MAT_usx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DBLMetadata type=&quot;text&quot; typeVersion=&quot;1.4&quot; id=&quot;ce61dd3decd6b8a8&quot; revision=&quot;0&quot;&gt;
        ///  &lt;identification&gt;
        ///    &lt;name&gt;Test Bundle Publication&lt;/name&gt;
        ///    &lt;nameLocal&gt;&lt;/nameLocal&gt;
        ///    &lt;abbreviation&gt;&lt;/abbreviation&gt;
        ///    &lt;abbreviationLocal&gt;&lt;/abbreviationLocal&gt;
        ///    &lt;scope&gt;&lt;/scope&gt;
        ///    &lt;description&gt;&lt;/description&gt;
        ///    &lt;dateCompleted&gt;&lt;/dateCompleted&gt;
        ///    &lt;systemId type=&quot;gbc&quot;&gt;&lt;/systemId&gt;
        ///    &lt;systemId type=&quot;tms&quot;&gt;&lt;/systemId&gt;
        ///    &lt;systemId type=&quot;reap&quot;&gt;&lt;/systemId&gt;
        ///    &lt;systemId t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metadata_xml {
            get {
                return ResourceManager.GetString("metadata_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;stylesheet&gt;
        ///  &lt;property name=&quot;font-family&quot;&gt;Cambria&lt;/property&gt;
        ///  &lt;property name=&quot;font-size&quot; unit=&quot;pt&quot;&gt;14&lt;/property&gt;
        ///  &lt;style id=&quot;id&quot; publishable=&quot;false&quot; versetext=&quot;false&quot;&gt;
        ///    &lt;name&gt;id - File - Identification&lt;/name&gt;
        ///    &lt;description&gt;File identification information (BOOKID, FILENAME, EDITOR, MODIFICATION DATE)&lt;/description&gt;
        ///    &lt;property name=&quot;text-align&quot;&gt;left&lt;/property&gt;
        ///  &lt;/style&gt;
        ///  &lt;style id=&quot;h&quot; publishable=&quot;true&quot; versetext=&quot;false&quot;&gt;
        ///    &lt;name&gt;h - File - Head [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles_xml {
            get {
                return ResourceManager.GetString("styles_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ldml&gt;
        ///	&lt;identity&gt;
        ///		&lt;version number=&quot;&quot; /&gt;
        ///		&lt;generation date=&quot;0001-01-01T00:00:00Z&quot; /&gt;
        ///		&lt;language type=&quot;en&quot; /&gt;
        ///	&lt;/identity&gt;
        ///	&lt;characters&gt;
        ///		&lt;exemplarCharacters&gt;[]&lt;/exemplarCharacters&gt;
        ///		&lt;exemplarCharacters type=&quot;punctuation&quot;&gt;[!%-/\:;=?\[\]\u00B0\u00D7\u200C\u200D\u2013\u2014\u2018\u2019\u201C\u201D\u2303{...}]&lt;/exemplarCharacters&gt;
        ///		&lt;special xmlns:sil=&quot;urn://www.sil.org/ldml/0.1&quot;&gt;
        ///			&lt;sil:exemplarCharacters type=&quot;footnotes&quot;&gt;[]&lt;/sil:exemplarCharacters&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v2_eng_en_ldml {
            get {
                return ResourceManager.GetString("v2_eng_en_ldml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] v2_eng_lds {
            get {
                object obj = ResourceManager.GetObject("v2_eng_lds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] v2_MAT_usx {
            get {
                object obj = ResourceManager.GetObject("v2_MAT_usx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DBLMetadata version=&quot;2.0&quot; id=&quot;9879dbb7cfe39e4d&quot; revision=&quot;5&quot;&gt;
        ///  &lt;identification&gt;
        ///    &lt;name&gt;World English Bible&lt;/name&gt;
        ///    &lt;description&gt;English: World English Bible Bible with Deuterocanon&lt;/description&gt;
        ///    &lt;abbreviation&gt;WEB&lt;/abbreviation&gt;
        ///    &lt;scope&gt;Bible with Deuterocanon&lt;/scope&gt;
        ///    &lt;dateCompleted&gt;2014-09-24&lt;/dateCompleted&gt;
        ///    &lt;bundleProducer&gt;Paratext/7.6.54.99&lt;/bundleProducer&gt;
        ///    &lt;systemId type=&quot;gbc&quot;&gt;
        ///      &lt;id&gt;546a4d9f5117ad7230055b04&lt;/id&gt;
        ///    &lt;/systemId&gt;
        ///    &lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v2_metadata_xml {
            get {
                return ResourceManager.GetString("v2_metadata_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;stylesheet&gt;
        ///  &lt;property name=&quot;font-family&quot;&gt;Gentium Basic&lt;/property&gt;
        ///  &lt;property name=&quot;font-size&quot; unit=&quot;pt&quot;&gt;14&lt;/property&gt;
        ///  &lt;style id=&quot;id&quot; publishable=&quot;false&quot; versetext=&quot;false&quot;&gt;
        ///    &lt;name&gt;id - File - Identification&lt;/name&gt;
        ///    &lt;description&gt;File identification information (BOOKID, FILENAME, EDITOR, MODIFICATION DATE)&lt;/description&gt;
        ///    &lt;property name=&quot;text-align&quot;&gt;left&lt;/property&gt;
        ///  &lt;/style&gt;
        ///  &lt;style id=&quot;ide&quot; publishable=&quot;false&quot; versetext=&quot;false&quot;&gt;
        ///    &lt;name&gt;ide -  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v2_styles_xml {
            get {
                return ResourceManager.GetString("v2_styles_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] v2_versification_vrs {
            get {
                object obj = ResourceManager.GetObject("v2_versification_vrs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] versification_vrs {
            get {
                object obj = ResourceManager.GetObject("versification_vrs", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
