[General]
codepage=65001
AutoKeyboardSwitching=T
DialogFontsize=14
LowerCaseLetters=abcdefghijklmnopqrstuvwxyz
NoCaseLetters=
RTL=F
UpperCaseLetters=ABCDEFGHIJKLMNOPQRSTUVWXYZ
errors=
font=Cambria
name=English
separator=/
size=14

[Checking]

[Characters]
Chr01=a/A
Chr02=b/B
Chr03=c/C
Chr04=d/D
Chr05=e/E
Chr06=f/F
Chr07=g/G
Chr08=h/H
Chr09=i/I
Chr10=j/J
Chr11=k/K
Chr12=l/L
Chr13=m/M
Chr14=n/N
Chr15=o/O
Chr16=p/P
Chr17=q/Q
Chr18=r/R
Chr19=s/S
Chr20=t/T
Chr21=u/U
Chr22=v/V
Chr23=w/W
Chr24=x/X
Chr25=y/Y
Chr26=z/Z

[Punctuation]
bracket=(/) [/] {/} </> <</>>
diacritics=
diacriticsfollow=No
final=, . ; : ? ! ) ] } > >> -- *
footnotes=
initial=( [ { < << --
medial=-'´—
miscellaneous=0 1 2 3 4 5 6 7 8 9 " '
sentence=. : ? !
versesegments=a b c d e f g h i j k l m n o p q r s t u v w x y z aa bb cc dd ee ff gg hh ii jj kk ll mm nn oo pp qq rr ss tt uu vv ww xx yy zz
