//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaso.Services.Dictionary.SampleClient.Properties {


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default {
			get {
				return defaultInstance;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("en")]
		public string WritingSystemIdForDefinitions {
			get {
				return ((string)(this["WritingSystemIdForDefinitions"]));
			}
			set {
				this["WritingSystemIdForDefinitions"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("xgs")]
		public string WritingSystemIdForWords {
			get {
				return ((string)(this["WritingSystemIdForWords"]));
			}
			set {
				this["WritingSystemIdForWords"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("E:\\Users\\John\\Documents\\WeSay\\NooSupu\\noosupu.lift")]
		public string PathToDictionary {
			get {
				return ((string)(this["PathToDictionary"]));
			}
			set {
				this["PathToDictionary"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("c:\\wesay\\output\\debug\\wesay.app.exe")]
		public string PathToApplication {
			get {
				return ((string)(this["PathToApplication"]));
			}
			set {
				this["PathToApplication"] = value;
			}
		}
	}
}
