//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaso.UI.WindowsForms.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palaso.UI.WindowsForms.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Bitmap cc_BY_88x31 {
			get {
				object obj = ResourceManager.GetObject("cc_BY_88x31", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap DeleteMessageBoxButtonImage {
			get {
				object obj = ResourceManager.GetObject("DeleteMessageBoxButtonImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
		///&lt;?xml-stylesheet href=&quot;../OLAC_doc.xsl&quot; type=&quot;text/xsl&quot;?&gt;
		///&lt;!DOCTYPE OLAC_doc SYSTEM &quot;../OLAC_doc.dtd&quot;&gt;
		///&lt;OLAC_doc&gt;
		///  &lt;header&gt;
		///     &lt;status code=&quot;adopted&quot; type=&quot;recommendation&quot;/&gt;
		///     &lt;!-- Promoted to Adopted on 2008-12-19 --&gt;
		///    &lt;title&gt;OLAC Role Vocabulary&lt;/title&gt;
		///    &lt;baseName&gt;role&lt;/baseName&gt;
		///    &lt;issued&gt;20060406&lt;/issued&gt;
		///    &lt;previousIssued&gt;20031010&lt;/previousIssued&gt;
		///    &lt;abstract&gt;
		///      &lt;p&gt;Role is an attribute of both the Creator and Contributor elements. (Please note that Dublin
		///    [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string OlacRoles {
			get {
				return ResourceManager.GetString("OlacRoles", resourceCulture);
			}
		}

		internal static System.Drawing.Bitmap RecycleBin {
			get {
				object obj = ResourceManager.GetObject("RecycleBin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap RemoveGridRowHot {
			get {
				object obj = ResourceManager.GetObject("RemoveGridRowHot", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap RemoveGridRowNormal {
			get {
				object obj = ResourceManager.GetObject("RemoveGridRowNormal", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
