//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaso {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resource {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resource() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palaso.Resource", typeof(Resource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Id	Part2B	Part2T	Part1	Scope	Type	Ref_Name
		///aaa				I	L	Ghotuo
		///aab				I	L	Alumu-Tesu
		///aac				I	L	Ari
		///aad				I	L	Amal
		///aae				I	L	Arbëreshë Albanian
		///aaf				I	L	Aranadan
		///aag				I	L	Ambrak
		///aai				I	L	Arifama-Miniafia
		///aak				I	L	Ankave
		///aal				I	L	Afade
		///aam				I	L	Aramanik
		///aan				I	L	Anambé
		///aao				I	L	Algerian Saharan Arabic
		///aap				I	L	Pará Arára
		///aaq				I	E	Eastern Abnaki
		///aar	aar	aar	aa	I	L	Afar
		///aas				I	L	Aasáx
		///aat				I	L	Arvanitika Albanian
		///aau				I	L	Abau
		///aaw				I	L	Solong
		///aax				I	L	Mandobo  [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string languageCodes {
			get {
				return ResourceManager.GetString("languageCodes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to #
		///# ISO639 15924 - Codes for the representation of names of scripts
		///#             Codes pour la représentation des noms d’écritures
		///# Format:
		///#             Code;N°;English Name;Nom français;PVA;Date
		///#
		///
		///Arab;160;Arabic;arabe;Arabic;2004-05-01
		///Armn;230;Armenian;arménien;Armenian;2004-05-01
		///Avst;134;Avestan;avestique;;2007-07-15
		///Bali;360;Balinese;balinais;Balinese;2006-10-10
		///Batk;365;Batak;batak;;2004-05-01
		///Beng;325;Bengali;bengalî;Bengali;2004-05-01
		///Blis;550;Blissymbols;symboles Bliss;;2004-05-01
		/// [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string scriptNames {
			get {
				return ResourceManager.GetString("scriptNames", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up language subtags
		///
		/// Type: language
		///Subtag: aa
		///Description: Afar
		///Added: 2005-10-16
		///%%
		///Type: language
		///Subtag: ab
		///Description: Abkhazian
		///Added: 2005-10-16
		///Suppress-Script: Cyrl
		///%%
		///Type: language
		///Subtag: ae
		///Description: Avestan
		///Added: 2005-10-16
		///%%
		/// </summary>
		internal static string IanaSubtags
		{
			get
			{
				return ResourceManager.GetString("ianaSubtagRegistry", resourceCulture);
			}
		}
	}
}
