//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.DblBundle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.DblBundle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///    &lt;xsl:output indent=&quot;yes&quot;/&gt;
        ///
        ///    &lt;xsl:template match=&quot;/DBLMetadata&quot;&gt;
        ///        &lt;xsl:choose&gt;
        ///            &lt;xsl:when test=&quot;type/medium/text() != &apos;text&apos; or not(@version) or @version != &apos;2.0&apos;&quot;&gt;
        ///                &lt;error code=&quot;bad-type-or-version&quot;&gt;Not text 2.0 metadata&lt;/error&gt;
        ///            &lt;/xsl:when&gt;
        ///            &lt;xsl:otherwise&gt;
        ///                &lt;xsl:copy&gt;
        ///                    &lt;xsl:attribute name=&quot;type&quot;&gt;text&lt;/xsl:attribute&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_2_0_to_1_5_xsl {
            get {
                return ResourceManager.GetString("text_2_0_to_1_5_xsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///    &lt;xsl:output indent=&quot;yes&quot;/&gt;
        ///
        ///    &lt;xsl:template match=&quot;/DBLMetadata&quot;&gt;
        ///        &lt;xsl:choose&gt;
        ///            &lt;xsl:when test=&quot;type/medium/text() != &apos;text&apos; or not(@version) or @version != &apos;2.1&apos;&quot;&gt;
        ///                &lt;error code=&quot;bad-type-or-version&quot;&gt;Not text 2.1 metadata&lt;/error&gt;
        ///            &lt;/xsl:when&gt;
        ///            &lt;xsl:otherwise&gt;
        ///                &lt;xsl:copy&gt;
        ///                    &lt;xsl:attribute name=&quot;type&quot;&gt;text&lt;/xsl:attribute&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_2_1_to_1_5_xsl {
	        get {
		        return ResourceManager.GetString("text_2_1_to_1_5_xsl", resourceCulture);
	        }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///    &lt;xsl:output indent=&quot;yes&quot;/&gt;
        ///
        ///    &lt;xsl:template match=&quot;/DBLMetadata&quot;&gt;
        ///        &lt;xsl:choose&gt;
        ///            &lt;xsl:when test=&quot;type/medium/text() != &apos;text&apos; or not(@version) or @version != &apos;2.2&apos;&quot;&gt;
        ///                &lt;error code=&quot;bad-type-or-version&quot;&gt;Not text 2.2 metadata&lt;/error&gt;
        ///            &lt;/xsl:when&gt;
        ///            &lt;xsl:otherwise&gt;
        ///                &lt;xsl:copy&gt;
        ///                    &lt;xsl:attribute name=&quot;type&quot;&gt;text&lt;/xsl:attribute&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_2_2_to_1_5_xsl {
	        get {
		        return ResourceManager.GetString("text_2_2_to_1_5_xsl", resourceCulture);
	        }
        }
    }
}
