//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Scripture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.Scripture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;English&quot;
        ///# Version=2.0
        ///#
        ///# modifications by Reinier de Blois 13/March/2012
        ///# modified mappings Psalms by adding verse #0 to the mappings
        ///# many of the subscripts that are part of verses 1,2 in the original text end up as verse #0 in English translations
        ///
        ///# modifications by Studge 26/June/2009
        ///# book definitions are for all books printed in any English of Spanish Bible
        ///# this includes books for Protestant, Catholic and Protestant-Catholic-EasternOrthodox Interconfessional editions        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eng_vrs {
            get {
                return ResourceManager.GetString("eng_vrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Septuagint&quot;
        ///# Version=1.6
        ///# 
        ///# modifications by Studge 26/ June/ 2009
        ///# This should include the versifications for Bibles which follow LXX versificatio mainly Orthodox Bibles. [Studge]
        ///#
        ///# List of books, chapters, verses
        ///# One line per book.
        ///# One entry for each chapter.
        ///# Verse number is the maximum verse number for that chapter.
        ///# See the lines containing =&apos;s below for verse mappings.
        ///#
        ///# modifications by Reinier 20/ April/ 2010
        ///# all data that are not part of the LXX itself [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lxx_vrs {
            get {
                return ResourceManager.GetString("lxx_vrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Original&quot; 
        ///# Version=1.200
        ///# (not a very good name but I have not heard a better suggestion)
        ///#
        ///# modifications by Studge 26/June/2009
        ///#
        ///# BHS versification for OT, UBS GNT versification for NT
        ///# following the Masoretic order
        ///# OT translations using Masorteic verse structures should map onto this text
        ///# NT versifications maps onto Nestle-Aland
        ///#
        ///# List of books, chapters, verses
        ///# One line per book.
        ///# One entry for each chapter.
        ///# Verse number is the maximum verse number for t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string org_vrs {
            get {
                return ResourceManager.GetString("org_vrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Russian Protestant&quot;
        ///# Version=1.4
        ///#
        ///# This is the versification used by the &quot;Canonical&quot; (Protestant) edition of the Russian Synodal Bible
        ///# Initial version provided by Peter_Kirk@sil.org
        ///# Corrected 27/May/2003 by matjaz.crnivec@drustvo-svds.si:
        ///#   Number of vss: ISA 3; REV 12
        ///#   Mappings: LEV 14; 1KI 22; 1CH 12; NEH 7; ISA 3; 2CO 11; REV 13
        ///#
        ///# List of books, chapters, verses
        ///# One line per book.
        ///# One entry for each chapter.
        ///# Verse number is the maximum verse number for th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rsc_vrs {
            get {
                return ResourceManager.GetString("rsc_vrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Russian Orthodox&quot;
        ///# Version=1.3
        ///#
        ///# This is the versification used by the Orthodox (or &quot;non-canonical&quot;) edition of the Russian Synodal Bible
        ///# Initial version provided by Peter_Kirk@sil.org
        ///# Corrected 27/May/2003 by matjaz.crnivec@drustvo-svds.si:
        ///#   Number of vss: 2CH 37; PSA 114; ISA 3; REV 12; 2ES (whole book added),
        ///#   Mappings: LEV 14; 1KI 22; 1CH 12; 2CH 37; NEH 7; PSA 114; ISA 3; 2CO 11; REV 13; 2ES 7; 10
        ///#
        ///# modifications by Studge 26/June/2009
        ///# amended by HAB April 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rso_vrs {
            get {
                return ResourceManager.GetString("rso_vrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Vulgate&quot;
        ///# Version=1.4
        ///# 
        ///# modifications by Studge 26/June/2009
        ///# this is for Bibles which follow the versification of the Vulgate, mainly Catholic Bibles
        ///# therefore this includes deuterocanonical books from Vulgate and Latin manuscripts
        ///# Vulgate projects in Paratext are VUL83 (Stuttgart text) and NVL98 (Nova Vulgata) [Studge]
        ///#
        ///# mapping for XXA -&gt; PSA has been deleted  [requested by RdB - Barb]
        ///# XXB has been moved to LAO [Barb] Jan 2011
        ///#
        ///# No mapping done for TOB, JDT and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vul_vrs {
            get {
                return ResourceManager.GetString("vul_vrs", resourceCulture);
            }
        }
    }
}
