//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaso.Reporting {


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
	internal sealed partial class UsageMemory : global::System.Configuration.ApplicationSettingsBase {

		private static UsageMemory defaultInstance = ((UsageMemory)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UsageMemory())));

		public static UsageMemory Default {
			get {
				return defaultInstance;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Launches {
			get {
				return ((int)(this["Launches"]));
			}
			set {
				this["Launches"] = value;
			}
		}
	}
}
