//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.WritingSystems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageRegistryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageRegistryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.WritingSystems.LanguageRegistryResources", typeof(LanguageRegistryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;full&quot;: &quot;aa-Latn-ET&quot;, 
        ///        &quot;iana&quot;: &quot;Afar&quot;, 
        ///        &quot;iso639_3&quot;: &quot;aar&quot;, 
        ///        &quot;localname&quot;: &quot;Qafar&quot;, 
        ///        &quot;name&quot;: &quot;Afar&quot;, 
        ///        &quot;names&quot;: [
        ///            &quot;Afaraf&quot;, 
        ///            &quot;Qafar&quot;, 
        ///            &quot;Qafar af&quot;, 
        ///            &quot;ʿAfár af&quot;
        ///        ], 
        ///        &quot;region&quot;: &quot;ET&quot;, 
        ///        &quot;regionname&quot;: &quot;Ethiopia&quot;, 
        ///        &quot;regions&quot;: &quot;DJ ER&quot;, 
        ///        &quot;sldr&quot;: true, 
        ///        &quot;tag&quot;: &quot;aa&quot;, 
        ///        &quot;tags&quot;: [
        ///            &quot;aa-ET&quot;, 
        ///            &quot;aa-Latn&quot;
        ///        ]
        ///    }, 
        ///    {
        ///        &quot;full&quot;: &quot;aa- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string alltags {
            get {
                return ResourceManager.GetString("alltags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-12-07T09:35:24Z.
        /// </summary>
        internal static string AllTagsTime {
            get {
                return ResourceManager.GetString("AllTagsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-Date: 2018-08-08
        ///%%
        ///Type: language
        ///Subtag: aa
        ///Description: Afar
        ///Added: 2005-10-16
        ///%%
        ///Type: language
        ///Subtag: ab
        ///Description: Abkhazian
        ///Added: 2005-10-16
        ///Suppress-Script: Cyrl
        ///%%
        ///Type: language
        ///Subtag: ae
        ///Description: Avestan
        ///Added: 2005-10-16
        ///%%
        ///Type: language
        ///Subtag: af
        ///Description: Afrikaans
        ///Added: 2005-10-16
        ///Suppress-Script: Latn
        ///%%
        ///Type: language
        ///Subtag: ak
        ///Description: Akan
        ///Added: 2005-10-16
        ///Scope: macrolanguage
        ///%%
        ///Type: language
        ///Subtag: am
        ///Description: Amharic
        ///Adde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ianaSubtagRegistry {
            get {
                return ResourceManager.GetString("ianaSubtagRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa	aar
        ///ab	abk
        ///af	afr
        ///ak	aka
        ///am	amh
        ///ar	ara
        ///an	arg
        ///as	asm
        ///av	ava
        ///ae	ave
        ///ay	aym
        ///az	aze
        ///ba	bak
        ///bm	bam
        ///be	bel
        ///bn	ben
        ///bi	bis
        ///bo	bod
        ///bs	bos
        ///br	bre
        ///bg	bul
        ///ca	cat
        ///cs	ces
        ///ch	cha
        ///ce	che
        ///cu	chu
        ///cv	chv
        ///kw	cor
        ///co	cos
        ///cr	cre
        ///cy	cym
        ///da	dan
        ///de	deu
        ///dv	div
        ///dz	dzo
        ///el	ell
        ///en	eng
        ///eo	epo
        ///et	est
        ///eu	eus
        ///ee	ewe
        ///fo	fao
        ///fa	fas
        ///fj	fij
        ///fi	fin
        ///fr	fra
        ///fy	fry
        ///ff	ful
        ///gd	gla
        ///ga	gle
        ///gl	glg
        ///gv	glv
        ///gn	grn
        ///gu	guj
        ///ht	hat
        ///ha	hau
        ///sh	hbs
        ///he	heb
        ///hz	her
        ///hi	hin
        ///ho	hmo
        ///hr	hrv
        ///hu	hun
        ///hy	hye
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoToThreeCodes {
            get {
                return ResourceManager.GetString("TwoToThreeCodes", resourceCulture);
            }
        }
    }
}
