//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.WritingSystems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageRegistryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageRegistryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.WritingSystems.LanguageRegistryResources", typeof(LanguageRegistryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryID	Name	Area
        ///AD	Andorra	Europe
        ///AE	United Arab Emirates	Asia
        ///AF	Afghanistan	Asia
        ///AG	Antigua and Barbuda	Americas
        ///AI	Anguilla	Americas
        ///AL	Albania	Europe
        ///AM	Armenia	Asia
        ///AO	Angola	Africa
        ///AR	Argentina	Americas
        ///AS	American Samoa	Pacific
        ///AT	Austria	Europe
        ///AU	Australia	Pacific
        ///AW	Aruba	Americas
        ///AZ	Azerbaijan	Asia
        ///BA	Bosnia and Herzegovina	Europe
        ///BB	Barbados	Americas
        ///BD	Bangladesh	Asia
        ///BE	Belgium	Europe
        ///BF	Burkina Faso	Africa
        ///BG	Bulgaria	Europe
        ///BH	Bahrain	Asia
        ///BI	Burundi	Africa
        ///BJ	Beni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryCodes {
            get {
                return ResourceManager.GetString("CountryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-Date: 2015-03-06
        ///%%
        ///Type: language
        ///Subtag: aa
        ///Description: Afar
        ///Added: 2005-10-16
        ///%%
        ///Type: language
        ///Subtag: ab
        ///Description: Abkhazian
        ///Added: 2005-10-16
        ///Suppress-Script: Cyrl
        ///%%
        ///Type: language
        ///Subtag: ae
        ///Description: Avestan
        ///Added: 2005-10-16
        ///%%
        ///Type: language
        ///Subtag: af
        ///Description: Afrikaans
        ///Added: 2005-10-16
        ///Suppress-Script: Latn
        ///%%
        ///Type: language
        ///Subtag: ak
        ///Description: Akan
        ///Added: 2005-10-16
        ///Scope: macrolanguage
        ///%%
        ///Type: language
        ///Subtag: am
        ///Description: Amharic
        ///Adde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ianaSubtagRegistry {
            get {
                return ResourceManager.GetString("ianaSubtagRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LangID	CountryID	LangStatus	Name
        ///aaa	NG	L	Ghotuo
        ///aab	NG	L	Alumu-Tesu
        ///aac	PG	L	Ari
        ///aad	PG	L	Amal
        ///aae	IT	L	Albanian, Arbëreshë
        ///aaf	IN	L	Aranadan
        ///aag	PG	L	Ambrak
        ///aah	PG	L	Arapesh, Abu’
        ///aai	PG	L	Miniafia Oyan
        ///aak	PG	L	Ankave
        ///aal	CM	L	Afade
        ///aan	BR	L	Anambé
        ///aao	DZ	L	Arabic, Algerian Saharan Spoken
        ///aap	BR	L	Arára, Pará
        ///aaq	US	L	Abenaki, Eastern
        ///aar	ET	L	Afar
        ///aas	TZ	L	Aasáx
        ///aat	GR	L	Albanian, Arvanitika
        ///aau	PG	L	Abau
        ///aaw	PG	L	Solong
        ///aax	ID	L	Mandobo Atas
        ///aaz	ID	L	Amarasi
        ///aba	CI	L	Abé
        ///abb	CM	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LanguageCodes {
            get {
                return ResourceManager.GetString("LanguageCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LangID	CountryID	NameType	Name
        ///aaa	NG	L	Ghotuo
        ///aab	NG	D	Alumu
        ///aab	NG	D	Tesu
        ///aab	NG	DA	Arum
        ///aab	NG	L	Alumu-Tesu
        ///aab	NG	LA	Alumu
        ///aab	NG	LA	Arum-Cesu
        ///aab	NG	LA	Arum-Chessu
        ///aab	NG	LA	Arum-Tesu
        ///aac	PG	D	Serea
        ///aac	PG	L	Ari
        ///aad	PG	L	Amal
        ///aad	PG	LA	Alai
        ///aae	IT	D	Calabrian Albanian
        ///aae	IT	D	Campo Marino Albanian
        ///aae	IT	D	Central Mountain Albanian
        ///aae	IT	D	Molise Albanian
        ///aae	IT	D	Sicilian Albanian
        ///aae	IT	L	Albanian, Arbëreshë
        ///aae	IT	LA	Arbëreshë
        ///aaf	IN	L	Aranadan
        ///aaf	IN	LA	Aranatan
        ///aaf	IN	LA	E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LanguageIndex {
            get {
                return ResourceManager.GetString("LanguageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!DOCTYPE supplementalData SYSTEM &quot;../../common/dtd/ldmlSupplemental.dtd&quot;&gt;
        ///&lt;!--
        ///Copyright © 1991-2014 Unicode, Inc.
        ///CLDR data files are interpreted according to the LDML specification (http://unicode.org/reports/tr35/)
        ///For terms of use, see http://www.unicode.org/copyright.html
        ///--&gt;
        ///&lt;supplementalData&gt;
        ///    &lt;version number=&quot;$Revision$&quot;/&gt;
        ///    &lt;generation date=&quot;$Date$&quot;/&gt;
        ///    &lt;likelySubtags&gt;
        ///		&lt;likelySubtag from=&quot;aa&quot; to=&quot;aa_Latn_ET&quot;/&gt;
        ///		&lt;!--{ Afar; ?; ? } =&gt; { A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string likelySubtags {
            get {
                return ResourceManager.GetString("likelySubtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa	aar
        ///ab	abk
        ///af	afr
        ///ak	aka
        ///am	amh
        ///ar	ara
        ///an	arg
        ///as	asm
        ///av	ava
        ///ae	ave
        ///ay	aym
        ///az	aze
        ///ba	bak
        ///bm	bam
        ///be	bel
        ///bn	ben
        ///bi	bis
        ///bo	bod
        ///bs	bos
        ///br	bre
        ///bg	bul
        ///ca	cat
        ///cs	ces
        ///ch	cha
        ///ce	che
        ///cu	chu
        ///cv	chv
        ///kw	cor
        ///co	cos
        ///cr	cre
        ///cy	cym
        ///da	dan
        ///de	deu
        ///dv	div
        ///dz	dzo
        ///el	ell
        ///en	eng
        ///eo	epo
        ///et	est
        ///eu	eus
        ///ee	ewe
        ///fo	fao
        ///fa	fas
        ///fj	fij
        ///fi	fin
        ///fr	fra
        ///fy	fry
        ///ff	ful
        ///gd	gla
        ///ga	gle
        ///gl	glg
        ///gv	glv
        ///gn	grn
        ///gu	guj
        ///ht	hat
        ///ha	hau
        ///sh	hbs
        ///he	heb
        ///hz	her
        ///hi	hin
        ///ho	hmo
        ///hr	hrv
        ///hu	hun
        ///hy	hye
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoToThreeCodes {
            get {
                return ResourceManager.GetString("TwoToThreeCodes", resourceCulture);
            }
        }
    }
}
