
name: Libpalaso CI workflow

on:
  pull_request:
    branches: [ feature/nuget ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe (Windows OS)
      uses: microsoft/setup-msbuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      if: ${{ matrix.os == 'windows-latest' }}

    # Run the unit tests
    - name: Restore and Build
      run: msbuild build/Palaso.proj /t:Build /p:Configuration=Debug /p:Platform="Any CPU"

    - name: Test
      run: msbuild build/Palaso.proj /t:TestOnly /p:Configuration=Debug /p:Platform="Any CPU"
      
    - name: Test Report
      uses: MirrorNG/nunit-reporter@v1.0.5
      if: always()
      with:
        path: Output/**/TestResults.xml
        access-token: ${{ secrets.BOGUS_TOKEN }}
        
    - name: Test Report2
      uses: MirrorNG/nunit-reporter@v1.0.5
      if: always()
      with:
        path: Output/**/TestResults.xml
        access-token: ${{ secrets.TEST_RESULT_PUBLISH_TOKEN }}
