//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.mp3</string>
  <string>.wav</string>
  <string>.wma</string>
  <string>.aac</string>
  <string>.aiff</string>
  <string>.ogg</string>
  <string>.flac</string>
  <string>.m4a</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AudioFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AudioFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.wmv</string>
  <string>.avi</string>
  <string>.mpg</string>
  <string>.mpeg</string>
  <string>.mpa</string>
  <string>.asf</string>
  <string>.mov</string>
  <string>.mp4</string>
  <string>.mts</string>
  <string>.m4v</string>
  <string>.m2v</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VideoFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VideoFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.txt</string>
  <string>.doc</string>
  <string>.docx</string>
  <string>.odt</string>
  <string>.rtf</string>
  <string>.htm</string>
  <string>.html</string>
  <string>.pdf</string>
  <string>.fwdata</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TextFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TextFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.jpg</string>
  <string>.jpeg</string>
  <string>.gif</string>
  <string>.tif</string>
  <string>.png</string>
  <string>.bmp</string>
  <string>.dib</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImageFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImageFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.tab</string>
  <string>.btab</string>
  <string>.cmf</string>
  <string>.dls</string>
  <string>.midi</string>
  <string>.mid</string>
  <string>.imf</string>
  <string>.ly</string>
  <string>.mxl</string>
  <string>.niff</string>
  <string>.mmf</string>
  <string>.mml</string>
  <string>.rmf</string>
  <string>.mdx</string>
  <string>.xmf</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MusicalNotationFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MusicalNotationFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.fwdata</string>
  <string>.mdf</string>
  <string>.lift</string>
  <string>.sfm</string>
  <string>.oxes</string>
  <string>.osis</string>
  <string>.xml</string>
  <string>.prj</string>
  <string>.mdb</string>
  <string>.bak</string>
  <string>.ssf</string>
  <string>.sty</string>
  <string>.lds</string>
  <string>.lng</string>
  <string>.db</string>
  <string>.uml</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatasetFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatasetFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.ttf</string>
  <string>.map</string>
  <string>.tec</string>
  <string>.otf</string>
  <string>.cs</string>
  <string>.cpp</string>
  <string>.h</string>
  <string>.exe</string>
  <string>.dll</string>
  <string>.bat</string>
  <string>.com</string>
  <string>.kmx</string>
  <string>.kmn</string>
  <string>.sh</string>
  <string>.py</string>
  <string>.ikp</string>
  <string>.cct</string>
  <string>.inkey</string>
  <string>.js</string>
  <string>.css</string>
  <string>.msi</string>
  <string>.mak</string>
  <string>.pl</string>
  <string>.resx</string>
  <string>.rc</string>
  <string>.sql</string>
  <string>.vb</string>
  <string>.vbs</string>
  <string>.xaml</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SoftwareAndFontFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SoftwareAndFontFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.ppt</string>
  <string>.pptx</string>
  <string>.odp</string>
  <string>.pptm</string>
  <string>.potx</string>
  <string>.potm</string>
  <string>.pot</string>
  <string>.pps</string>
  <string>.ppsx</string>
  <string>.ppsm</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PresentationFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PresentationFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.zip</string>\r\n  <string>.fwbackup</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ZipFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ZipFileExtensions"]));
            }
        }
    }
}
